package com.foo;

/**
 * Created by amotzhoshen on 26/02/2017.
 */
public enum MessageErrorCode{
	VALIDATION_ERROR,
	SEARCH_NO_ITEMS_FOUND,
	SEARCH_ITEMS_FOUND_MISSING_ENTITIES,
	SEARCH_NO_RELATED_ITEMS_FOUND,
	NOT_ALLOWED,
	BOUNCED_EMAIL,
	NEARLY_VALID,
	WHY_NEED_THIS,
	MANDATORY_END_CONVERSATION;
}
